name: Deploy to FTP Production

on:
  push:
    branches:
      - main

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: 🔧 Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: 📥 Install dependencies
        run: npm install

      - name: 🛠 Build styles
        run: npm run sass

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER_PROD }}
          username: ${{ secrets.FTP_USERNAME_PROD }}
          password: ${{ secrets.FTP_PASSWORD_PROD }}
          local-dir: ./
          server-dir: /wp-content/themes/venus/
          exclude: |
            **/node_modules/**
            **/.git*
            **/.git*/**
            **/.github/**
            **/node_modules/**
            package.json
            package-lock.json
            gulpfile.js
